# примечание:
# если нужно задать большой длинный вопрос из нескольких строк используйте \n для перевода на следующую строку
questions:
  question-1:
    question: "2+2?"
    prize: 3000
    answers:
      - "4"

  question-2:
    question: "2+3?"
    prize: 5000
    answers:
      - "5"
# период игры в секундах (1200 = каждые 10 мин)
period: 1200


# {QUESTION} - вопрос
# {PRIZE} - приз
# {WINNER} - победитель
# {ANSWERS} - все правильные ответы
# {ANSWER} - правильный ответ от игрока
broadcast:
  start-game:
    - "ЧАТ ИГРА"
    - " "
    - "ответьте на вопрос: {QUESTION}"
    - "приз: {PRIZE}"

  end-game:
    - "ЧАТ ИГРА"
    - " "
    - "игрок {WINNER} выиграл"
    - "правильные ответы: {ANSWERS}"

  time-left:
    - "ЧАТ ИГРА"
    - " "
    - "Увы, никто не ответил на вопрос."
    - "Ответ был: {ANSWERS}"
# длительность вопроса
question-time: 30 # секунд